version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=docker
      - DATABASE_PASSWORD=docker
      - DATABASE_NAME=miniproject
    ports:
      - "8000:8000"
    volumes:
      - .:/app/classes

  database:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: miniproject
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      - database
    ports:
      - "8080:8080"

volumes:
  postgres_data:
